### ISSUE TITLE
! LaTeX Error: File `bidi.sty' not found.

### ISSUE THREAD

**Issue by andrecastro0o** [wdka-publicationSt/print-kiosk-ii#2]
Error log 
```
print_queue contains: 3 articles
all_pages.json
queue.tmp.json
*queue.tmp.html written*
*latex.metadata.yaml written*
> /home/andre/Documents/WdKA/BS/print-kiosk-ii/queue2pdf.py(175)check_pandoc_version()
-> request = subprocess.Popen(["pandoc", "--version"], stdout=subprocess.PIPE)
(Pdb) c
Error producing PDF.
! LaTeX Error: File `bidi.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Emergency stop.
<read *>

l.77 ^^M

*done! tmp/queue.2019-05-31_10-31-05.pdf written*
```
However  `tmp/queue.2019-05-31_10-31-05.pdf`  does not get written due to the error

**Comment by andrecastro0o** [comment]
According to [this tex.stackexchange. thread(https://tex.stackexchange.com/questions/412513/problem-building-bidi-package)

> Apparently Debian is still providing outdated packages etc. I recommend to use the TeXLive net installer, which allows for updating the whole TeX distribution at any time (apart from the period where TL is frozen from April to June) – user31729 Jan 28 '18 at 9:01 

And if I place
`\listfiles` at the top a of a latex file and run it with `xelatex test.latex` It replies
> This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016/Debian) (preloaded format=xelatex 2018.2.18)  31 MAY 2019 11:52
And no bidi package is found.

----

## installing TeX Live via net install
* remove previous installation: [instructions](https://tex.stackexchange.com/questions/95483/how-to-remove-everything-related-to-tex-live-for-fresh-install-on-ubuntu#95502)
* Get [netinstall tar ball](http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz)
* extract tar bar: `tar xfvz `
* follow the [installation instructions](http://tug.org/texlive/quickinstall.html)
* add texlive path to the user's executables path by appending to `~/.bashrc` `PATH=/usr/local/texlive/2019/bin/x86_64-linux:$PATH`

Test: using file test.latex
```
\listfiles
\documentclass{memoir}
\usepackage{longtable}
\usepackage{hyperref}
\usepackage{bidi}                                                                                                                                                     

\begin{document}
  \begin{longtable}{l}
    x
  \end{longtable}
\end{document}
```
Run: `xelatex test.latex`

**Comment by andrecastro0o** [comment]
However PDF is being produced without an issue in commit [623c222](https://github.com/wdka-publicationSt/print-kiosk-ii/commit/623c22246383886792846dc054fb8061063836b7) 

And in that commit `latex.twocolumns.tex` **does not use bidi**
 
See [diff between 623c2224 and Master](https://github.com/wdka-publicationSt/print-kiosk-ii/compare/623c22246383886792846dc054fb8061063836b7)

@andrecastro0o  wonders if this was something changed with @manettab during the last week.

In any case. **Issue has been solved by:**
* using bable + polyglossia texlive packages in branch:bug/LaTex-template file: emplates/latex.twocolumns.tex
* using: netinstall of **texlive??** @manettab would be nice if you could try it in your system since you have installed texlive from debian package. And I have used the netinstall in both my machine and the Pi. cheers

**Comment by ghost** [comment]
the debian texlive package still triggered the bidi error: 

! LaTeX Error: File `bidi.sty' not found.
